# ------------------------------------------------------------------------------------
# Spring BOOT Admin Server Configuration
#
# Config: https://codecentric.github.io/spring-boot-admin/2.4.3/#_configuration_options
#
# Para configurar la seguridad: https://www.baeldung.com/spring-boot-admin
# ------------------------------------------------------------------------------------
server:
  port: 9007
  servlet:
    context-path: /
    application-display-name: MicroServices Manager Wrapper Admin

application:
  title: MicroServices Manager Wrapper Admin



logging:
  file:
    name: "com.atsistemas.rsi.manager-apis-admin"
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"



spring:
  application:
    name: MicroServices Manager Wrapper Admin
  # profiles:
  #   active:
  #     - secure



  # ------------------------------------------
  # Spring BOOT Admin Client Configuration
  #
  # Más info: https://codecentric.github.io/spring-boot-admin/2.4.3/#spring-boot-admin-client
  # ------------------------------------------
  boot:
    admin:
      client:
        # If enabled or not
        enabled: false
      server:
        # If enabled or not
        enabled: true
      monitor:
        default-timeout: 1m
        info-interval: 1m
        info-lifetime: 1m
        status-interval: 1m
        status-lifetime: 1m
      ui:
        title: WSO2 API Manager Wrapper Admin

  jmx:
    enabled: true



management:
  # Per Actuator EndPoint
  endpoint:
    health:
      show-components: always
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    # + Expose all endpoints by default
    web:
      exposure:
        ### ALL: include: "*"
        include: "*"
        exclude:
        ### SELECT:
        # include: beans,configprops,env,health,info,loggers,shutdown
        # exclude: auditevents,caches,conditions,flyway,httptrace,integrationgraph,liquibase,metrics,mappings,scheduledtasks,sessions,threaddump
        ### Additional endpoints are only available for Spring MVC, Spring WebFlux, or Jersey: heapdump,jolokia,logfile,prometheus
      cors:
        allowed-methods:
          - GET
          - POST
        allowed-origins:
          - http://localhost
          - http://localhost:4200
          - http://localhost:8080
          - http://localhost:9000
          - http://localhost:9007
endpoints:
  shutdown:
    enabled: true


